### ISSUE TITLE
Truth of Delayed objects is not supported

### ISSUE THREAD

**Issue by tlambert03** [DragaDoncila/napari-sentinel-zip#1]
sorry that my plugin installer GIF showed an error in this package 😂

here's the traceback that happened during plugin registration, culminating in:

`PluginRegistrationError: Error in plugin "napari-sentinel-zip": Truth of Delayed objects is not supported`

<details>
<summary>Traceback from napari</summary>

```
===================== Errors for plugin 'napari-sentinel-zip' =====================

  napari version: 0.3.6.dev6 g7e45c01e.d20200624
  plugin package: napari-sentinel-zip
         version: 0.1.1
          module: <module 'napari_sentinel_zip.napari_sentinel_zip' from '/Users/talley/miniconda3/envs/napdev/lib/python3.8/site-packages/napari_sentinel_zip/napari_sentinel_zip.py'>


ERROR #1:  Error in plugin %22napari-sentinel-zip%22: Truth of Delayed objects is not supported 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Dropbox (HMS)/Python/forks/napari-plugin-engine/napari_plugin_engine/manager.py in _load_and_register(self=<napari_plugin_engine.manager.PluginManager object>, mod_name='napari_sentinel_zip.napari_sentinel_zip', plugin_name='napari-sentinel-zip')
    279         try:
--> 280             return self.register(module, plugin_name)
        self.register = <bound method PluginManager.register of <napari_plugin_engine.manager.PluginManager object at 0x121810190>>
        module = <module 'napari_sentinel_zip.napari_sentinel_zip' from '/Users/talley/miniconda3/envs/napdev/lib/python3.8/site-packages/napari_sentinel_zip/napari_sentinel_zip.py'>
        plugin_name = 'napari-sentinel-zip'
    281         except PluginError:

~/Dropbox (HMS)/Python/forks/napari-plugin-engine/napari_plugin_engine/manager.py in register(self=<napari_plugin_engine.manager.PluginManager object>, namespace=<module 'napari_sentinel_zip.napari_sentinel_zip...ages/napari_sentinel_zip/napari_sentinel_zip.py'>, name='napari-sentinel-zip')
    329         hookcallers = []
--> 330         for hookimpl in iter_implementations(namespace, self.project_name):
        hookimpl = <HookImplementation plugin='napari-sentinel-zip' spec='napari_get_reader'>
        global iter_implementations = <function iter_implementations at 0x121835670>
        namespace = <module 'napari_sentinel_zip.napari_sentinel_zip' from '/Users/talley/miniconda3/envs/napdev/lib/python3.8/site-packages/napari_sentinel_zip/napari_sentinel_zip.py'>
        self.project_name = 'napari'
    331             hookimpl.plugin_name = plugin_name

~/Dropbox (HMS)/Python/forks/napari-plugin-engine/napari_plugin_engine/manager.py in iter_implementations(namespace=<module 'napari_sentinel_zip.napari_sentinel_zip...ages/napari_sentinel_zip/napari_sentinel_zip.py'>, project_name='napari')
    893         hookimpl_opts = getattr(method, tag, None)
--> 894         if not hookimpl_opts:
        hookimpl_opts = Delayed('getattr-7b5dcbad7e4e800f6ea0a3fa70275808')
    895             continue

~/miniconda3/envs/napdev/lib/python3.8/site-packages/dask/delayed.py in __bool__(self=Delayed('getattr-7b5dcbad7e4e800f6ea0a3fa70275808'))
    562     def __bool__(self):
--> 563         raise TypeError(%22Truth of Delayed objects is not supported%22)
        global TypeError = undefined
    564 

TypeError: Truth of Delayed objects is not supported

The above exception was the direct cause of the following exception:

PluginRegistrationError                   Traceback (most recent call last)
~/Dropbox (HMS)/Python/forks/napari-plugin-engine/napari_plugin_engine/manager.py in discover(self=<napari_plugin_engine.manager.PluginManager object>, ignore_errors=True)
    210 
    211             try:
--> 212                 if self._load_and_register(mod_name, name):
        self._load_and_register = <bound method PluginManager._load_and_register of <napari_plugin_engine.manager.PluginManager object at 0x121810190>>
        mod_name = 'napari_plugin_engine'
        name = 'napari_plugin_engine'
    213                     count  = 1
    214             except PluginError as e:

~/Dropbox (HMS)/Python/forks/napari-plugin-engine/napari_plugin_engine/manager.py in _load_and_register(self=<napari_plugin_engine.manager.PluginManager object>, mod_name='napari_sentinel_zip.napari_sentinel_zip', plugin_name='napari-sentinel-zip')
    282             raise
    283         except Exception as exc:
--> 284             raise PluginRegistrationError(
        global PluginRegistrationError = <class 'napari_plugin_engine.exceptions.PluginRegistrationError'>
        global plugin = undefined
        module = <module 'napari_sentinel_zip.napari_sentinel_zip' from '/Users/talley/miniconda3/envs/napdev/lib/python3.8/site-packages/napari_sentinel_zip/napari_sentinel_zip.py'>
        plugin_name = 'napari-sentinel-zip'
        global cause = undefined
        exc = undefined
    285                 plugin=module, plugin_name=plugin_name, cause=exc
    286             )

PluginRegistrationError: Error in plugin %22napari-sentinel-zip%22: Truth of Delayed objects is not supported
================================================================================
```
</details>

`napari --info`

```sh
napari: 0.3.6.dev6+g7e45c01e.d20200624
Platform: macOS-10.13.6-x86_64-i386-64bit
Python: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27)  [Clang 9.0.1 ]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.17.2
VisPy: 0.6.4

GL version:  2.1 NVIDIA-10.33.0 387.10.10.15.15.108
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari_plugin_engine: 0.1.7.dev2+gfca1657
  - svg: 0.1.3
```

**Comment by jni** [comment]
@tlambert03 everything works fine with published and master versions of napari and napari-plugin-engine! Are you doing something funkier with discovery in napari/napari#1357?

If you look at the plugin implementation here:

https://github.com/DragaDoncila/napari-sentinel-zip/blob/master/napari_sentinel_zip/napari_sentinel_zip.py

there is a function decorated with `dask.delayed`, but it is not used/registered as a plugin implementation, it is called within get_reader. That should be allowed, right?

**Comment by tlambert03** [comment]
I’ll take a closer look!  Definitely possible it’s on my end

**Comment by tlambert03** [comment]
hmm, I'm getting similar errors in a fresh environment with napari 0.3.5,  py 3.8, dask 2.19, npe 0.1.6, ...
how can I test it locally?  when you say works fine, what are you testing?

**Comment by DragaDoncila** [comment]
It should work with napari 0.3.5 and npe 0.1.6, that's how we tested it locally.

Potentially it's the data - the plugin reads, very specifically, zips containing raw tiffs of Sentinel satellite images at various timepoints. The images are huge, so in order to test it right now, the only real option is for you to use the test tile, [here](https://github.com/DragaDoncila/napari-sentinel-zip/tree/master/napari_sentinel_zip/_tests).

That folder contains tiny 50*50 pixel images in the correct format. You should be able to drag in the whole tile, or an individual zip, and it should be fine.

It's on my list to write a tutorial that includes instructions to download full size tiles direct from the Sentinel repository.

**Comment by tlambert03** [comment]
I'm not even loading data.  I'm just opening napari, going to the "list plugins" ... it doesn't show up, then I got to errors and the dask error is there.  I'll try the test tile

**Comment by DragaDoncila** [comment]
Okay so now I'm able to recreate the behaviour, because that same error shows up for me as well if I go to plugin errors.
However, if I drag in folders, napari does use the plugin without errors in the terminal.

**Comment by tlambert03** [comment]
yeah, I was just able to see that too.  data loads fine.  I think I know what's going on here... it _IS_ partially loading, but it _also_ runs into an error during registration.    There's actually a note about this sort of thing in the pluggy source code [here](https://github.com/pytest-dev/pluggy/blob/f17598a7b422a8a7566a258d2f79fae5fde6b78a/src/pluggy/manager.py#L99-L101), where they point out that there is the possibility for plugin manager state to be altered (i.e. some of the hooks can be loaded) while errors are also occurring.  we can look into fixing that.
in any case, I think there might be issues in both  (I actually saw this delayed issue in one of my own things recently) but I'll investigate and get back to you

**Comment by jni** [comment]
@tlambert03 do you understand what's actually happening? From what I can tell:

https://github.com/napari/napari-plugin-engine/blob/fca165798b535b955d38d316145dd7d4c2e47e10/napari_plugin_engine/manager.py#L882-L898

I presume you're loading that dask.delayed decorated function (ie 'name' is [`ziptiff2array`](https://github.com/DragaDoncila/napari-sentinel-zip/blob/3ff4c0960e558ea8ff6d8c16d760f07cb28df1c8/napari_sentinel_zip/napari_sentinel_zip.py#L76-L101)), then you grab the tag (`napari_get_reader`?), which somehow results in a Delayed object??? That sounds like Pluggy decorated the wrong function? It's very confusing to me...

One potential fix though would be to change that line to `if hookimpl_opts is None:`?

**Comment by tlambert03** [comment]
ahhh, interesting.  `getattr(<delayed_function>, 'napari_impl', None)` does not return None.  it returns `Delayed('getattr-23ff3632759ce8d849d3748a26b91175')`.  that's the problem.  I can fix it.  thanks!

**Comment by tlambert03** [comment]
didn't know that about delayed.  to be explicit:
```python
import dask.delayed

@dask.delayed
def test(): 
    return

print(getattr(test, 'asdfs', None)) 
# Delayed('getattr-20b67d8951200f0a31e404a5201aa399')
```

who knew?

**Comment by DragaDoncila** [comment]
That's actually really surprising!

**Comment by jni** [comment]
That's super crazy!

**Comment by jni** [comment]
Yeah it's just like WTH:

```python
In [1]: import dask

In [2]: @dask.delayed
   ...: def return1():
   ...:     return 1
   ...:

In [3]: return1.compute
Out[3]: <bound method DaskMethodsMixin.compute of Delayed('return1-e05cf8c2-9873-44d6-b87d-e82e2ec8da97')>

In [4]: return1.hello
Out[4]: Delayed('getattr-5cbda656b64e0894b07a0f96d384ed13')
```

I'm sure there's a good use case for this, but I can't see it yet.

**Comment by DragaDoncila** [comment]
Resolved by updating napari-plugin-engine.
